export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";

export const GET_SINGLE_JOBS_REQUEST = "GET_SINGLE_JOBS_REQUEST";
export const GET_SINGLE_JOBS_SUCCESS = "GET_SINGLE_JOBS_SUCCESS";
export const GET_SINGLE_JOBS_FAILURE = "GET_SINGLE_JOBS_FAILURE";
