export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";

export const SAVE_JOBS_REQUEST = "SAVE_JOBS_REQUEST";
export const SAVE_JOBS_SUCCESS = "SAVE_JOBS_SUCCESS";
export const GET_SAVE_JOBS_SUCCESS = "GET_SAVE_JOBS_SUCCESS";
export const GET_APPLY_JOBS_SUCCESS = "GET_APPLY_JOBS_SUCCESS";
export const SAVE_JOBS_FAILURE = "SAVE_JOBS_FAILURE";

export const APPLY_JOBS_REQUEST = "APPLY_JOBS_REQUEST";
export const APPLY_JOBS_SUCCESS = "APPLY_JOBS_SUCCESS";
export const APPLY_JOBS_FAILURE = "APPLY_JOBS_FAILURE";

export const GET_SINGLE_JOBS_REQUEST = "GET_SINGLE_JOBS_REQUEST";
export const GET_SINGLE_JOBS_SUCCESS = "GET_SINGLE_JOBS_SUCCESS";
export const GET_SINGLE_JOBS_FAILURE = "GET_SINGLE_JOBS_FAILURE";
